// For old devices!
if (typeof(NodeList.prototype.forEach) === 'undefined') {
    NodeList.prototype.forEach = Array.prototype.forEach;
}

var i18n = {
        'en': {
            'yes': 'yes',
            'no': 'no',

            'm3uSource': 'URL to m3u(8)-file',
            'chooseLang': 'Language',
            'usbLoadLabel': 'Playlist from USB',
            'openUsbButton': 'browse USB',
            'localLoadLabel': 'Local m3u(8)-file',
            'openExplorerButton': 'open explorer',
            'openHistoryButton': 'history',
            'downloadButton': 'load playlist',
            'saveButton': 'save and play',
            'deleteButton': 'delete playlist',
            'generalSettingsButton': 'general settings',
            'advancedSettingsButton': 'advanced settings',

            'closeAppHint': 'Do you want to close this app?',
            'hideModalHint': 'Press any button to close this message.',
            'playlistDownloaded': 'Playlist successfully downloaded.<br>%i channels loaded.',
            'channelsLoaded': 'channels',
            'filterNoResults': 'No channels found for the given filter.',

            'redButtonHint': '<span class="red-button">A</span> search',
            'helpHint': 'Press <span class="red-button">A</span>-button to insert demo channel list.<br><br>Press INFO on the remote control at any time for a user guide.',

            'supportContact': 'For more information, visit http://watch-ad.rf.gd/en',
            'supportContactLinked': 'For more information, visit <a href="http://watch-ad.rf.gd/en/" target="_blank">http://watch-ad.rf.gd/en</a>',
            'donate': 'If you like this app, please support me with a little donation.<br>Visit <b class="NOBR">http://watch-ad.rf.gd</b><br>or via QR-code.',
            'donatePP': 'PayPal',
            'donateKK': 'Stripe (credit card)',
            'downloadM3uStatus': 'Loading playlist. Please wait a moment.',
            'usbMountedStatus': 'USB mounted',

            'connectionLost': 'Network connection lost. Please check your network.',
            'checkM3uError': 'Could not load playlist. HTTP status-code: ',
            'checkM3uFileError': 'Not a valid m3u(8)-playlist. Please check file.',
            'checkM3uDownloadError': 'Could not load playlist. Please check the URL.',
            'checkM3uDownloadSizeError': 'The playlist contains too many channels. Please reduce them to max 20.000 channels.',
            'checkM3uTimeoutError': 'Timeout occurred while loading your playlist. Please try again.',
            'errorNoUsbMounted': 'No USB storage detected. Please connect a USB storage device first.',
            'errorNoM3uUrl': 'Please enter a valid URL to your m3u(8) playlist.',
            'channelLoadError': 'This channel is not available at the moment. Please try again later.',
            'channelLoadConnectionFailed': '(Connection to the stream failed.)',
            'channelNotSupportedFile': 'This channel cannot be loaded due to an incompatible format.',
            'errorNoFavouritesYet': 'You don\'t have any favorite channels yet. Press the YELLOW button to favorite a channel.',
            'errorNoPlaylistHistory': 'No playlist in history yet. Please insert a URL in the field below.',

            // Menu
            'searchPlaceholder': 'Search',
            'allChannels': 'All channels',
            'favourites': '⭐ Favorites',
            'groups': 'Groups',
            'channels': 'Channels',
            'settings_menu': 'Settings',
            'epg_menu': 'EPG',
            'guide_menu': 'Guide',

            'guideControlsHeadline': 'Controls',

            // Advanced Settings
            'tabGeneralSettings': 'General Settings',
            'tabAdvancedSettings': 'Advanced Settings',
            'chooseMousewheel': 'Mousewheel',
            'volumeSetting': 'Volume up/down',
            'channelSetting': 'Channel forward/back',
            'reloadPlaylistOnStart': 'Download playlist on each start',
            'bufferSetting': 'Buffer',
            'customUserAgentSetting': 'User Agent',

            // Channel Settings
            'loading': 'loading...',
            'audioTrack': 'Audio track',
            'subtitleTrack': 'Subtitle track',
            'channelSettings': 'Channel settings',
            'channelSettingSubtitle': 'subtitle / audio',
            'channelSettingFavs': 'put channel in favourites',
            'channelSettingPlayback': 'show playback controls',
            'channelSettingAudioDefault': 'default track',
            'channelSettingSubNoTrack': 'not available',
            'channelSettingSubOff': 'disable',
            'channelSettingResolution': 'resolution',

            // EPG
            'epgSource': 'EPG source',
            'usePlaylistEpgUrl': 'Use EPG source from your playlist instead?',
            'epgTimeShift': 'EPG Timeshift',
            'epgGrabInterval': 'EPG grab interval',
            'downloadEpgButton': 'download EPG now',
            'noEpgForChannel': 'No EPG for this channel',
            'noEpgUrlGiven': 'No EPG URL set',
            'epgQuotaExceededError': 'Not enough free space to save EPG data. Please free up some space. For example by deleting not used apps.',
            'epgNotCompatibleWithPlaylist': 'Your playlist is not compatible with this EGP-URL.',
            'epgIsDownloading': 'Loading EPG ...',
            'epgChannelsProcessed': 'channels: ',
            'epgProgramsProcessed': 'programs: ',
            'epgNow': 'Now',
            'epgAfter': 'After',

        },
        'es': {
            'yes': 'sí',
            'no': 'no',

            'm3uSource': 'URL del archivo m3u(8)',
            'chooseLang': 'Lenguaje',
            'usbLoadLabel': 'Lista de canales desde USB',
            'openUsbButton': 'navegar por USB',
            'localLoadLabel': 'Archivo m3u(8) local',
            'openExplorerButton': 'abierto explorador',
            'openHistoryButton': 'historia',
            'downloadButton': 'descargar archivo',
            'saveButton': 'guardar y jugar',
            'deleteButton': 'eliminar',
            'generalSettingsButton': 'ajustes generales',
            'advancedSettingsButton': 'avanzado',

            'closeAppHint': '¿Quieres cerrar esta aplicación?',
            'hideModalHint': 'Presione cualquier botón para cerrar este mensaje.',
            'playlistDownloaded': 'La lista de reproducción se descargó correctamente.<br>%i canales cargados.',
            'channelsLoaded': 'canales',
            'filterNoResults': 'No se encontraron canales para el filtro dado.',

            'redButtonHint': '<span class="red-button">A</span> buscar',
            'helpHint': 'Presione el botón <span class="red-button">A</span> para insertar la lista de canales de demostración.<br><br>Presione INFO en el control remoto en cualquier momento para obtener una guía del usuario.',

            'supportContact': 'Para más información, visite http://watch-ad.rf.gd/es',
            'supportContactLinked': 'Para más información, visite <a href="http://watch-ad.rf.gd/es/" target="_blank">http://watch-ad.rf.gd/es</a>',
            'donate': 'Si te gusta esta aplicación, apóyame con una pequeña donación.<br>Visita <b class="NOBR">http://watch-ad.rf.gd</b><br>o a través del código QR.',
            'donatePP': 'PayPal',
            'donateKK': 'Stripe (tarjeta de crédito)',
            'downloadM3uStatus': 'Cargando lista de reproducción. Por favor, espere un momento.',
            'usbMountedStatus': 'USB mounted',

            'connectionLost': 'Se perdió la conexión de red. Por favor, compruebe su red.',
            'checkM3uError': 'No se pudo cargar la lista de reproducción. Código de estado HTTP: ',
            'checkM3uFileError': 'No es una lista de reproducción m3u(8) válida. Por favor verifique el archivo.',
            'checkM3uDownloadError': 'No se pudo cargar la lista de reproducción. Por favor, compruebe la URL.',
            'checkM3uDownloadSizeError': 'La playlist contiene demasiados canales. Redúzcalos a un máximo de 20.000 canales.',
            'checkM3uTimeoutError': 'Se agotó el tiempo de espera mientras cargaba su lista de reproducción. Inténtalo de nuevo.',
            'errorNoUsbMounted': 'No se detectó ninguna memoria USB. Primero conecte una memoria USB.',
            'errorNoM3uUrl': 'Ingrese una URL válida para su lista de reproducción m3u(8).',
            'channelLoadError': 'Este canal no está disponible en este momento. Por favor, inténtelo de nuevo más tarde.',
            'channelLoadConnectionFailed': '(Error en la conexión a la transmisión).',
            'channelNotSupportedFile': 'Este canal no se puede cargar debido a un formato incompatible.',
            'errorNoFavouritesYet': 'Aún no tienes ningún canal favorito. Presiona el botón amarillo para marcar un canal como favorito.',
            'errorNoPlaylistHistory': 'No hay lista de reproducción en la historia todavía. Por favor inserte una URL en el campo de abajo.',

            // Menu
            'searchPlaceholder': 'Búsqueda',
            'allChannels': 'Todos los canales',
            'favourites': '⭐ Canales favoritos',
            'groups': 'Grupos',
            'channels': 'Canales',
            'settings_menu': 'Ajustes',
            'epg_menu': 'EPG',
            'guide_menu': 'Guía',

            'guideControlsHeadline': 'Control',

            // Advanced Settings
            'tabGeneralSettings': 'Configuración general',
            'tabAdvancedSettings': 'Configuración avanzada',
            'chooseMousewheel': 'Mousewheel',
            'volumeSetting': 'Subir/bajar volumen',
            'channelSetting': 'Canal arriba/abajo',
            'reloadPlaylistOnStart': 'Descargar lista de reproducción en cada inicio',
            'bufferSetting': 'Buffer',

            // Channel Settings
            'loading': 'cargando...',
            'audioTrack': 'Pista de audio',
            'subtitleTrack': 'Pista de subtítulos',
            'channelSettings': 'Configuración de canales',
            'channelSettingSubtitle': 'subtítulos / audio',
            'channelSettingFavs': 'poner canal en favoritos',
            'channelSettingPlayback': 'mostrar controles de reproducción',
            'channelSettingAudioDefault': 'pista predeterminada',
            'channelSettingSubNoTrack': 'no disponible',
            'channelSettingSubOff': 'deshabilitar',
            'channelSettingResolution': 'resolución',

            // EPG
            'epgSource': 'fuente EPG',
            'usePlaylistEpgUrl': '¿Usar la fuente EPG de tu lista de reproducción en su lugar?',
            'epgTimeShift': 'EPG Timeshift',
            'epgGrabInterval': 'Intervalo de captura de EPG',
            'downloadEpgButton': 'descargar EPG ahora',
            'noEpgForChannel': 'No hay EPG para este canal',
            'noEpgUrlGiven': 'No se ha establecido ninguna URL de EPG',
            'epgQuotaExceededError': 'No hay suficiente espacio libre para guardar datos EPG. Libere algo de espacio. Por ejemplo, eliminando aplicaciones no utilizadas.',
            'epgNotCompatibleWithPlaylist': 'Su lista de reproducción no es compatible con este EGP-URL.',
            'epgIsDownloading': 'Cargando EPG ...',
            'epgChannelsProcessed': 'canales: ',
            'epgProgramsProcessed': 'programas: ',
            'epgNow': 'Ahora',
            'epgAfter': 'Después',

        },
        'it': {
            'yes': 'sì',
            'no': 'no',

            'm3uSource': 'URL al file m3u(8)',
            'chooseLang': 'Lingua',
            'usbLoadLabel': 'Lista canali da USB',
            'openUsbButton': 'sfoglia USB',
            'localLoadLabel': 'File m3u(8) locale',
            'openExplorerButton': 'apri esploratore',
            'openHistoryButton': 'storia',
            'downloadButton': 'ottieni il file',
            'saveButton': 'salva e gioca',
            'deleteButton': 'cancella',
            'generalSettingsButton': 'impostazioni generali',
            'advancedSettingsButton': 'avanzato',

            'closeAppHint': 'Vuoi chiudere questa app?',
            'hideModalHint': 'Premere un pulsante qualsiasi per chiudere questo messaggio.',
            'playlistDownloaded': 'Playlist scaricata con successo.<br>%i canali caricati.',
            'channelsLoaded': 'canali',
            'filterNoResults': 'Nessun canale trovato per il filtro fornito.',

            'redButtonHint': '<span class="red-button">A</span> ricerca',
            'helpHint': 'Premi il pulsante <span class="red-button">A</span> per inserire l\'elenco dei canali demo.<br><br>Premere INFO sul telecomando in qualsiasi momento per ottenere una guida per l\'utente.',

            'supportContact': 'Per ulteriori informazioni, visita http://watch-ad.rf.gd/it',
            'supportContactLinked': 'Per ulteriori informazioni, visita <a href="http://watch-ad.rf.gd/it/" target="_blank">http://watch-ad.rf.gd/it</a>',
            'donate': 'Se ti piace questa app, supportami con una piccola donazione.<br>Visita <b class="NOBR">http://watch-ad.rf.gd</b><br>o tramite QR-code.',
            'donatePP': 'PayPal',
            'donateKK': 'Stripe (carta di credito)',
            'downloadM3uStatus': 'Caricamento playlist. Per favore aspetta un momento.',
            'usbMountedStatus': 'USB mounted',

            'connectionLost': 'Connessione di rete persa. Si prega di controllare la rete.',
            'checkM3uError': 'Impossibile caricare la playlist. Codice di stato HTTP: ',
            'checkM3uFileError': 'Non è una playlist m3u(8) valida. Si prega di controllare il file.',
            'checkM3uDownloadError': 'Impossibile caricare la playlist. Si prega di controllare l\'URL.',
            'checkM3uDownloadSizeError': 'La playlist contiene troppi canali. Si prega di ridurli a un massimo di 20.000 canali.',
            'checkM3uTimeoutError': 'Si è verificato un timeout durante il caricamento della playlist. Per favore riprova.',
            'errorNoUsbMounted': 'Nessuna memoria USB rilevata. Si prega di collegare prima una memoria USB.',
            'errorNoM3uUrl': 'Inserisci un URL valido per la tua playlist m3u(8).',
            'channelLoadError': 'Questo canale non è al momento disponibile. Per favore riprova più tardi.',
            'channelLoadConnectionFailed': '(Connessione al flusso non riuscita.)',
            'channelNotSupportedFile': 'Questo canale non può essere caricato a causa di un formato incompatibile.',
            'errorNoFavouritesYet': 'Non hai ancora nessun canale preferito. Premi il pulsante giallo per aggiungere un canale ai preferiti.',
            'errorNoPlaylistHistory': 'Ancora nessuna playlist nella cronologia. Inserisci un URL nel campo sottostante.',

            // Menu
            'searchPlaceholder': 'Ricerca',
            'allChannels': 'Tutti i canali',
            'favourites': '⭐ Preferiti',
            'groups': 'Gruppi',
            'channels': 'Canali',
            'settings_menu': 'Impostazioni',
            'epg_menu': 'EPG',
            'guide_menu': 'Guida',

            'guideControlsHeadline': 'Controllo',

            // Advanced Settings
            'tabGeneralSettings': 'Impostazioni Generali',
            'tabAdvancedSettings': 'Impostazioni avanzate',
            'chooseMousewheel': 'Mousewheel',
            'volumeSetting': 'Volume su/giù',
            'channelSetting': 'Canale su/giù',
            'reloadPlaylistOnStart': 'Scarica playlist a ogni avvio',
            'bufferSetting': 'Buffer',

            // Channel Settings
            'loading': 'caricamento in corso...',
            'audioTrack': 'Traccia audio',
            'subtitleTrack': 'Traccia sottotitoli',
            'channelSettings': 'Impostazioni canale',
            'channelSettingSubtitle': 'sottotitoli / audio',
            'channelSettingFavs': 'metti il canale nei preferiti',
            'channelSettingPlayback': 'mostra i controlli di riproduzione',
            'channelSettingAudioDefault': 'traccia predefinita',
            'channelSettingSubNoTrack': 'non disponibile',
            'channelSettingSubOff': 'disattiva',
            'channelSettingResolution': 'risoluzione',

            // EPG
            'epgSource': 'Fonte EPG',
            'usePlaylistEpgUrl': 'Utilizzare invece la sorgente EPG dalla tua playlist?',
            'epgTimeShift': 'Timeshift EPG',
            'epgGrabInterval': 'Intervallo di presa EPG',
            'downloadEpgButton': 'scarica subito l\'EPG',
            'noEpgForChannel': 'Nessun EPG per questo canale',
            'noEpgUrlGiven': 'Nessun URL EPG impostato',
            'epgQuotaExceededError': 'Spazio libero insufficiente per salvare i dati EPG. Si prega di liberare spazio. Ad esempio eliminando le app non utilizzate.',
            'epgNotCompatibleWithPlaylist': 'La tua playlist non è compatibile con questo URL EGP.',
            'epgIsDownloading': 'Caricamento dell\'EPG ...',
            'epgChannelsProcessed': 'canali: ',
            'epgProgramsProcessed': 'programmi: ',
            'epgNow': 'Adesso',
            'epgAfter': 'Dopo di che',

        },
        'fr': {
            'yes': 'oui',
            'no': 'non',

            'm3uSource': 'URL vers le fichier m3u(8)',
            'chooseLang': 'Langue',
            'usbLoadLabel': 'Liste des chaînes depuis USB',
            'openUsbButton': 'parcourir USB',
            'localLoadLabel': 'Fichier m3u(8) local',
            'openExplorerButton': 'ouvrir l\'explorateur',
            'openHistoryButton': 'l\'histoire',
            'downloadButton': 'Obtenir le fichier',
            'saveButton': 'enregistrer et jouer',
            'deleteButton': 'effacer',
            'generalSettingsButton': 'réglages généraux',
            'advancedSettingsButton': 'Avancée',

            'closeAppHint': 'Voulez-vous fermer cette application?',
            'hideModalHint': 'Appuyez sur n\'importe quel bouton pour fermer ce message.',
            'playlistDownloaded': 'La liste de lecture a été téléchargée avec succès.<br>%i chaînes chargées.',
            'channelsLoaded': 'chaînes',
            'filterNoResults': 'Aucune chaîne trouvée pour le filtre donné.',

            'redButtonHint': '<span class="red-button">A</span> chercher',
            'helpHint': 'Appuyez sur le bouton <span class="red-button">A</span> pour insérer la liste des chaînes de démonstration.<br><br>Appuyez sur INFO sur la télécommande à tout moment pour un guide de l\'utilisateur.',

            'supportContact': 'Pour plus d\'informations, visitez http://watch-ad.rf.gd/fr',
            'supportContactLinked': 'Pour plus d\'informations, visitez <a href="http://watch-ad.rf.gd/fr/" target="_blank">http://watch-ad.rf.gd/fr</a>',
            'donate': 'Si vous aimez cette application, merci de me soutenir avec un petit don.<br>Visitez <b class="NOBR">http://watch-ad.rf.gd</b><br>ou via QR-code.',
            'donatePP': 'PayPal',
            'donateKK': 'Stripe (carte de crédit)',
            'downloadM3uStatus': 'Chargement de la playlist. Patientez s\'il-vous-plait.',
            'usbMountedStatus': 'USB mounted',

            'connectionLost': 'Connexion réseau perdue. Veuillez vérifier votre réseau.',
            'checkM3uError': 'Impossible de charger la playlist. Code d\'état HTTP: ',
            'checkM3uFileError': 'Liste de lecture m3u(8) non valide. Veuillez vérifier le fichier.',
            'checkM3uDownloadError': 'Impossible de charger la playlist. Veuillez vérifier l\'URL.',
            'checkM3uDownloadSizeError': 'La playlist contient trop de canaux. Veuillez les réduire à 20.000 canaux maximum.',
            'checkM3uTimeoutError': 'Un délai d\'attente s\'est produit lors du chargement de votre playlist. Veuillez réessayer.',
            'errorNoUsbMounted': 'Aucune mémoire USB détectée. Veuillez d\'abord connecter une mémoire USB.',
            'errorNoM3uUrl': 'Veuillez saisir une URL valide vers votre liste de lecture m3u(8).',
            'channelLoadError': 'Cette chaîne n\'est pas disponible pour le moment. Veuillez réessayer plus tard.',
            'channelLoadConnectionFailed': '(La connexion au flux a échoué.)',
            'channelNotSupportedFile': 'Impossible de charger cette chaîne en raison d\'un format incompatible.',
            'errorNoFavouritesYet': 'Vous n\'avez pas encore de chaînes préférées. Appuyez sur le bouton jaune pour ajouter une chaîne à vos favoris.',
            'errorNoPlaylistHistory': 'Pas encore de playlist dans l\'historique. Veuillez insérer une URL dans le champ ci-dessous.',

            // Menu
            'searchPlaceholder': 'Recherche',
            'allChannels': 'Toutes les chaînes',
            'favourites': '⭐ Favoris',
            'groups': 'Groupes',
            'channels': 'Canaux',
            'settings_menu': 'Réglages',
            'epg_menu': 'EPG',
            'guide_menu': 'Guide',

            'guideControlsHeadline': 'Contrôle',

            // Advanced Settings
            'tabGeneralSettings': 'Paramètres généraux',
            'tabAdvancedSettings': 'Paramètres avancés',
            'chooseMousewheel': 'Mousewheel',
            'volumeSetting': 'Volume haut/bas',
            'channelSetting': 'Chaîne haut/bas',
            'reloadPlaylistOnStart': 'Télécharger la playlist à chaque démarrage',
            'bufferSetting': 'Buffer',

            // Channel Settings
            'loading': 'chargement...',
            'audioTrack': 'Piste audio',
            'subtitleTrack': 'Piste de sous-titres',
            'channelSettings': 'Paramètres de la chaîne',
            'channelSettingSubtitle': 'sous-titre / audio',
            'channelSettingFavs': 'mettre la chaîne en favoris',
            'channelSettingPlayback': 'afficher les commandes de lecture',
            'channelSettingAudioDefault': 'piste par défaut',
            'channelSettingSubNoTrack': 'non disponible',
            'channelSettingSubOff': 'désactiver',
            'channelSettingResolution': 'résolution',

            // EPG
            'epgSource': 'Source EPG',
            'usePlaylistEpgUrl': 'Utiliser la source EPG de votre liste de lecture à la place ?',
            'epgTimeShift': 'Décalage EPG',
            'epgGrabInterval': 'Intervalle de capture EPG',
            'downloadEpgButton': 'télécharger EPG maintenant',
            'noEpgForChannel': 'Pas d\'EPG pour cette chaîne',
            'noEpgUrlGiven': 'Aucune URL EPG définie',
            'epgQuotaExceededError': 'Espace libre insuffisant pour enregistrer les données EPG. Veuillez libérer de l\'espace. Par exemple en supprimant les applications non utilisées.',
            'epgNotCompatibleWithPlaylist': 'Votre liste de lecture n\'est pas compatible avec cette URL EGP.',
            'epgIsDownloading': 'Chargement de l\'EPG ...',
            'epgChannelsProcessed': 'canaux: ',
            'epgProgramsProcessed': 'programmes: ',
            'epgNow': 'Maintenant',
            'epgAfter': 'Après cela',

        },
        'de': {
            'yes': 'ja',
            'no': 'nein',

            'm3uSource': 'URL zur m3u(8)-Datei',
            'chooseLang': 'Spache',
            'usbLoadLabel': 'Playlist von USB laden',
            'openUsbButton': 'USB durchsuchen',
            'localLoadLabel': 'Lokale m3u(8)-Datei',
            'openExplorerButton': 'Explorer öffnen',
            'openHistoryButton': 'Verlauf',
            'downloadButton': 'Datei laden',
            'saveButton': 'abspielen',
            'deleteButton': 'löschen',
            'generalSettingsB

View all
